---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины.
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету,
    размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и
    оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен быть с настройкой цветовой гаммы (светлая,темная)
  - Сайт должен быть с авторизацией через социальные сети.
  - Сайт должен автоматически подстраиваться под размеры и ориентацию экрана
    устройства (адаптивная верстка)
  - Магазин должен быть SPA приложением.
  - Сайт должен быть с возможностью удаления товара из корзины.
  - Сайт должен быть с переходом на страницу оплаты.
  - Сайт должен быть с возможностью оставть отзыв.
  - Магазин должен иметь страницы в социальных сетях.
